/*
*  This code was generated by Inca X
*
*  For more information please contact
*  support@incax.com
*  www.incax.com
*
*/
import net.jini.space.JavaSpace;
import net.jini.core.lease.Lease;

public class IIncaXClient {

    public static void main(String [] arg){
        try{
            
            System.out.println("Locating service...");
            
            long timeout=10000;

            /*IIncaX service=
              (IIncaX)ServiceLocator.getService(
                	IIncaX.class,timeout);
              */
             JavaSpace space = (JavaSpace)ServiceLocator.getService(JavaSpace.class, timeout); 
              
          //  System.out.println("Service proxy="+service);
            //using example generated method
    //        service.ping();
            System.out.println("Service pinged OK");
            space.write(new HelloWorldMessage(), null, Lease.FOREVER);
           // space.take(new HelloWorldMessage(), null, Lease.FOREVER);
      //      System.out.println("Message from service="+service.sayHelo());
            
            
        }catch(Exception ex){
        	ex.printStackTrace();
        }
    }

}
